### ISSUE TITLE
Multi-GPU Inference for 34B Model

### ISSUE THREAD

**Issue by serwansj** [magic-research/PLLaVA#48]
I am trying to run the 34B on 4x A100 GPUs, however, whenever I try to run inference it is throwing an error that there is not enough VRAM:

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.96 GiB. GPU 0 has a total capacity of 39.39 GiB of which 3.63 GiB is free. Including non-PyTorch memory, this process has 35.75 GiB memory in use.
```

It seems like the model is just using a single GPU even though all 4 are visible and I use `use_multi_gpus=True`. Could anyone tell me how to distribute it across multiple GPUs properly?

**Comment by Marlod390** [comment]
This works for me. Simply delete `model = model.to('cuda')` in demo after setting `use_multi_gpus=True`

**Comment by xing0047** [comment]
I managed to use multi gpus for inference (run pllava-13b on 2 RTX 4090s). But a new problem came up and i still have not solved it. 

`ValueError: The input provided to the model are wrong. The number of image tokens is 0 while the number of image given to the model is 1. This prevents correct indexing and breaks batch generation.`

 Has anyone solved this issue?
